### ISSUE TITLE
Cannot bytecompile 'fringe-helper.el'

### ISSUE THREAD

**Issue by syohex** [nschum/fringe-helper.el#1]
When I byte-compile `fringe-helper.el`, I got following error message.

```
fringe-helper.el:245:12:Error: Symbol's function definition is void: fringe-helper-convert
```

I think that `fringe-helper.el` uses `eval-when-compile` the wrong way.

**Comment by nschum** [comment]
Sorry for the wait. I've been sick.
This should do the trick.
