### ISSUE TITLE
Feature Request -- bitmap for the backslash

### ISSUE THREAD

**Issue by lawlist** [nschum/fringe-helper.el#3]
Emacs uses a backslash for wrapped lines when there is no right fringe.  When enabling the right fringe, however, there is no option for using a backslash.  It looks like your library has the potential for adding a backslash to the fringe, and if that is possible, then that would be a feature request to please consider for the future.

**Comment by nschum** [comment]
So you'd like to replace the wrapped-line arrow in the fringe with a backslash?

**Comment by lawlist** [comment]
Yes (if possible, that would be great).  Since the backslash `\` is the default symbol used by Emacs for wrapped text, I thought it might be a useful addition to your library.  Once fringes are enabled, the backslash symbol that we are all accustomed to seeing is no longer an available option.  Customization of the fringe (with bitmaps) is so far beyond the reach of novice Emacs users, a library such as yours comes in really handy.

**Comment by lawlist** [comment]
Thank you for adding those new features -- greatly appreciated!  :)
